settings:
  docker:
    parent_image: localhost:5000/zenml-base:latest
    dockerignore: .dockerignore
  orchestrator.sagemaker:
    synchronous: false
  
environment:
  ZENML_STORE_URL: http://zenml:8080

parameters:
  is_dummy: true # Change this to 'false' to run the evaluation on the full dataset.
