settings:
  docker:
    parent_image: localhost:5000/zenml-base:latest
    dockerignore: .dockerignore
  orchestrator.sagemaker:
    synchronous: false
  
environment:
  ZENML_STORE_URL: http://zenml:8080

parameters:
  artifact_names:
    - raw_documents
    - cleaned_documents
    - instruct_datasets
    - preference_datasets
