settings:
  docker:
    parent_image: localhost:5000/zenml-base:latest
    skip_build: true
  orchestrator.sagemaker:
    synchronous: false
  
environment:
  ZENML_STORE_URL: http://zenml:8080
  QDRANT_DATABASE_HOST: qdrant
    
parameters:
  author_full_names:
    - Bryan Berry
