settings:
  docker:
    parent_image: localhost:5000/zenml-base:latest
    dockerignore: .dockerignore
  orchestrator.sagemaker:
    synchronous: false
  
environment:
  ZENML_STORE_URL: http://zenml:8080

parameters:
  test_split_size: 0.1
  dataset_type: "instruction"
  push_to_huggingface: true
  dataset_id: beege/llmtwin
  mock: false
